FROM gcr.io/forgerock-io/ig:7.1.0

# Base image is using the forgerock user, switch to root for priviledged tasks
USER root
# RUN sed -i 's/stable\/updates/stable-security\/updates/' /etc/apt/sources.list
RUN cat /etc/apt/sources.list
RUN apt-get update -y
# install first libcrypt1 fix post-installation error and avoid fails docker build
# RUN apt-get install libcrypt1 -y
## install tools to edit the files in the container
RUN apt-get install nano vim -y
# test docker build from master
# Switching back to forgerock user, app will run as this
USER forgerock
# Create dir where secrets can be mounted into
RUN mkdir /var/ig/secrets
COPY --chown=forgerock:root bin/import-pem-certs.sh /home/forgerock
COPY --chown=forgerock:root lib /opt/ig/lib

# Copy all config files into the docker image.
# The default ig directory is /var/ig, and it expects subfolders config/ and scripts/ (if required)
COPY --chown=forgerock:root audit-schemas /var/ig/audit-schemas/
COPY --chown=forgerock:root scripts /var/ig/scripts/
COPY --chown=forgerock:root config /var/ig/config/
